# Generated by Django 5.2.2 on 2025-12-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_book_category_bookdescription_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='BOOKS/'),
        ),
        migrations.DeleteModel(
            name='BookDescription',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
