# Generated by Django 5.2.2 on 2025-12-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_remove_book_category_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_written',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
