# Generated by Django 5.2.2 on 2026-01-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_alter_book_description_alter_book_num_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='books/'),
        ),
    ]
